# Generated by Django 5.2.5 on 2025-11-27 18:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Imeundwa Lini')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_user1', to=settings.AUTH_USER_MODEL, verbose_name='Mshiriki wa Kwanza')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_user2', to=settings.AUTH_USER_MODEL, verbose_name='Mshiriki wa Pili')),
            ],
            options={
                'verbose_name': 'Chumba cha Chat',
                'verbose_name_plural': 'Vyumba vya Chat',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Maudhui ya Ujumbe')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Muda wa Kutuma')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom', verbose_name='Chumba')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Mtumaji')),
            ],
            options={
                'verbose_name': 'Ujumbe',
                'verbose_name_plural': 'Ujumbe',
                'ordering': ('timestamp',),
            },
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(fields=('user1', 'user2'), name='unique_chat_room'),
        ),
    ]
