# Generated by Django 5.2.5 on 2025-09-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ngo_role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Project Manager'), ('staff', 'Staff'), ('volunteer', 'Volunteer'), ('member', 'Member')], default='member', max_length=50),
        ),
    ]
