# Generated by Django 5.2.5 on 2025-11-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_memberprofile_membershippayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='control_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='control_number_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
