# Generated by Django 5.2.5 on 2025-11-11 17:12

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershippayment',
            name='year',
            field=models.PositiveIntegerField(default=content.models.current_year),
        ),
    ]
