# Generated by Django 5.2.5 on 2025-11-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_membershippayment_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('OG', 'Ongoing'), ('CP', 'Completed'), ('PL', 'Planned'), ('SS', 'Suspended')], default='OG', max_length=2, verbose_name='Project Status'),
        ),
    ]
