# Generated by Django 5.2.5 on 2025-11-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='subject',
            field=models.CharField(default='No Subject Provided', max_length=255, verbose_name='Subject / Title of Suggestion'),
        ),
    ]
