# Generated by Django 5.2.5 on 2025-11-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_suggestion_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='is_active_member',
        ),
    ]
