# Generated by Django 5.2.5 on 2025-11-26 12:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_remove_memberprofile_is_active_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ngo_role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('accountant', 'Accountant'), ('manager', 'Project Manager'), ('staff', 'Staff'), ('volunteer', 'Volunteer'), ('member', 'Member')], default='member', max_length=50),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('conference_link', models.URLField(blank=True, null=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='meetings_attended', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Meetings',
                'ordering': ['start_time'],
            },
        ),
    ]
